monitorSite: "sol"
sites:
  - name: "mars-lab"
    tags: ["region-mars", "dev"]
    groups:
      - name: "api-service.dev.com"
        hosts:
          - host: "127.0.0.1"
            tags: ["primary"]
          - host: "imina.lab.one"
            tags: ["primary"]
          - host: "imina.lab.two"
            tags: ["secondary"]
        checks:
          - port: "80"
            protocol: HTTP
            interval: 10s
            tags: ["api"]
            ruleMode: "any"
          - port: "22"
            protocol: TCP
            interval: 10s
            tags: ["ssh"]
            ruleMode: "any"
  - name: "pluto-prod"
    tags: ["region-pluto", "prod"]
    groups:
      - name: "api-service1.prod.com"
        hosts:
          - host: "127.0.0.1"
            tags: ["primary"]
          - host: "imin.prod.one"
            tags: ["secondary"]
        checks:
          - port: "800"
            protocol: HTTP
            interval: 10s
            tags: ["api"]
          - port: "22"
            protocol: TCP
            interval: 10s
            tags: ["ssh"]
      - name: "api-service2.prod.com"
        hosts:
          - host: "127.0.0.1"
            tags: ["primary"]
          - host: "imin.prod.one"
            tags: ["secondary"]
        checks:
          - port: "800"
            protocol: HTTP
            interval: 10s
            tags: ["api"]
          - port: "22"
            protocol: TCP
            interval: 10s
            tags: ["ssh"]
rules:
  - name: high_latency_warning
    condition: "responseTime > 1ms"
    tags: ["prod"]
    notifications: ["log"]  # This rule only sends log notifications
  - name: critical_downtime_prod
    condition: "downtime > 15s"
    tags: ["prod"]
    notifications: ["log"]  # This rule would use both (when slack is implemented)
  - name: critical_downtime_SSH
    condition: "downtime > 10s"
    tags: ["ssh"]
    notifications: ["log"]  # This rule would use both (when slack is implemented)
  - name: critical_downtime_SSH_warning
    condition: "downtime > 5s"
    tags: ["ssh-warning"]
    notifications: ["log"]  # This rule would use both (when slack is implemented)
notifications:
  - type: "log"    # Currently the only implemented type
